# Generated by Django 2.2.7 on 2020-04-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('message', models.TextField(verbose_name=500)),
            ],
            options={
                'db_table': 'faculty_table',
            },
        ),
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('message', models.TextField(verbose_name=500)),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
