# Generated by Django 2.2.7 on 2020-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_model',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='message',
            field=models.TextField(),
        ),
    ]
