# Generated by Django 2.2.7 on 2020-04-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200416_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_model',
            name='qualification',
        ),
    ]
